vim.keymap.set('n', '<leader>gs', vim.cmd.Git)
vim.keymap.set('n', '<leader>gd', vim.cmd.Gdiff)
vim.keymap.set('n', '<leader>gc', ':G commit<CR>')
vim.keymap.set('n', '<leader>gps', ':G push origin')
vim.keymap.set('n', '<leader>gpl', ':G pull origin')
